### ISSUE TITLE
Feat: Contact Us button

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#148]
### Describe the feature

**Create a Contact Us button, in the footer of the page.**

### Add ScreenShots

Add the button right beside Suppliers button.

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/cb48fa11-037e-46da-bca3-e7dc176be071)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a Hacktoberfest'23 contributor
- [ ] I want to work on this issue

**Comment by tusharshah21** [comment]
assign it to me, @dakshsinghrathore and please tell me how the icon should look.

**Comment by dakshsinghrathore** [comment]
@tusharshah21 assigned! Kindly drop a star😃

**Comment by vishalkj2002** [comment]
Can you please describe what should the contact us button do?
Like whether it should redirect to contact us page or directly mail to specified email id.
Can I also work on this?

**Comment by dakshsinghrathore** [comment]
@vishalkj2002 just redirect to the same page for now, will create a new issue for the page which it will redirect to in the future.

**Comment by tusharshah21** [comment]
hey @dakshsinghrathore this issue is already resolved for the home page

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/96661387/c21dc8b6-4b2d-4789-a396-6d2390e1b10c)

But for other pages, the Facebook and Instagram icons are also missing. Should I work on that too?

![image](https://github.com/dakshsinghrathore/ISRO-web/assets/96661387/1298703e-2e3e-4556-b42f-88bacfa94add)

**Comment by dakshsinghrathore** [comment]
yep, @tusharshah21 go ahead and create a new issue for the same, will assign it to you shortly

**Comment by tusharshah21** [comment]
@dakshsinghrathore Sorry, but I completed it here only. Please don't mind now
