### ISSUE TITLE
[FEAT]: Create Snap scrolling on homepage

### ISSUE THREAD

**Issue by dakshsinghrathore** [dakshsinghrathore/ISRO-web#22]
I'd like to incorporate a snap scrolling effect into the ISRO-web homepage. Here's a brief demonstration of the effect I'm aiming for. Please don't hesitate to reach out if you need any assistance! 🙌🏽

[screen-recorder-fri-oct-06-2023-12-57-14.webm](https://github.com/dakshsinghrathore/ISRO-web/assets/115932772/edae4bb3-17b9-4b0c-baef-81966c2dca40)

**Comment by sidhartha2002** [comment]
**Hey Bro, your website looks quite awesome 👍.  If you assign me this issue by doing the needful I will greatly appreciate. Thanks**

**Comment by dakshsinghrathore** [comment]
Assigned to you !!

**Comment by sidhartha2002** [comment]
I tried implementing snap-scroll on your web page, and I've encountered some technical challenges during the process. Despite my best efforts, the changes I've made seem to be causing issues that affect the overall functionality of the webpage.
I'm committed to delivering quality work, but it seems like this specific task might require expertise in a particular area of web development that I currently lack. I believe it would be best to reassign this task to someone who can address these challenges more effectively.
Btw thanks for giving me the opportunity.

**Comment by sidhartha2002** [comment]
After debugging alot... bro, I have successfully implemented the snap-scroll effect in the project. 

Here is the recording of my work :

https://github.com/dakshsinghrathore/ISRO-web/assets/73163725/fb1a002a-164a-416e-bd91-f81ea8785d74

Kindly verify it by accepting my pull request.
If you have any query do reach out to me or else do the needful.

Thanks.

**Comment by rohits-web03** [comment]
#### Hello! I would love to contribute to your project for the issue #22.
#### I have implemented the snap-scroll effect on the ISRO-web homepage keeping in mind the navbar and the footer so that it works properly.
#### Here's the demo:

https://github.com/dakshsinghrathore/ISRO-web/assets/132741672/da986b42-6920-44a0-9adc-20c38d0b7c05

#### Since this issue is not assigned to anyone.Can you please assign it to me?

**Comment by rohits-web03** [comment]
> #### Hello! I would love to contribute to your project for the issue #22.
> #### I have implemented the snap-scroll effect on the ISRO-web homepage keeping in mind the navbar and the footer so that it works properly.
> #### Here's the demo:
>  ISRO-web.homepage.snap-scroll.mp4 
> #### Since this issue is not assigned to anyone.Can you please assign it to me?

#### I can also **improve the snap-scrolling** effect further considering **mobile devices**(or any device with a touchpad).
#### Basically on a device with touchpad if we try to scroll through all sections with a single swing,then by default it tries to scroll past as many sections as possible and then stops but if you want that the user should go section by section while going through the website then I can make that happen as well.So that if the user tries to try to scroll through all sections with a single swing(on mobile) then the scroll would stop and snap on the next section and continue like that for next sections as well.

**Comment by dakshsinghrathore** [comment]
@rohits-web03 Assigned it to you !!

**Comment by dakshsinghrathore** [comment]
@sidhartha2002 Will assign you a different issue which you can work on shortly !

**Comment by rohits-web03** [comment]
> > #### Hello! I would love to contribute to your project for the issue #22.
> > #### I have implemented the snap-scroll effect on the ISRO-web homepage keeping in mind the navbar and the footer so that it works properly.
> > #### Here's the demo:
> > ISRO-web.homepage.snap-scroll.mp4
> > #### Since this issue is not assigned to anyone.Can you please assign it to me?
> 
> #### I can also **improve the snap-scrolling** effect further considering **mobile devices**(or any device with a touchpad).
> #### Basically on a device with touchpad if we try to scroll through all sections with a single swing,then by default it tries to scroll past as many sections as possible and then stops but if you want that the user should go section by section while going through the website then I can make that happen as well.So that if the user tries to try to scroll through all sections with a single swing(on mobile) then the scroll would stop and snap on the next section and continue like that for next sections as well.

#### for mobile devices do you want the default behaviour or want the user to go through the website section by section if they try to scroll through all sections with a single swing?

**Comment by dakshsinghrathore** [comment]
section by section !

**Comment by rohits-web03** [comment]
I have made the changes.Can you please check my pr and merge it.

**Comment by rohits-web03** [comment]
#### I have made the changes.Can you please check my pr and merge it.

**Comment by dakshsinghrathore** [comment]
Yes, will review it shortly, your patience is appreciated 😃
